name: build
on: [push]

env:
  RUST_BACKTRACE: full

jobs:
  build:
    name: build-musl-docker
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set Env
        run: |
          echo "::add-path::$HOME/.cargo/bin"

      - name: Install cargo
        run: |
          rustup self update
          rustup update

      - name: Install cross
        run: |
          cargo +stable install cross

      - name: Build server
        run: |
          cross build --target x86_64-unknown-linux-musl --release --bin bve-reborn-site
          ls target/x86_64-unknown-linux-musl/release

      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cwfitzgerald/bve-reborn-site

      - name: Deploy
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ./github/workflows/deploy.bash
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        if: github.ref == 'refs/heads/master'